export const listeningQuestionNumber: any[] = [
  {
    title: "Part1",
    children: [
      { idx: 1, isReview: false, checked: true },
      { idx: 2, isReview: false, checked: false },
      { idx: 3, isReview: false, checked: false },
      { idx: 4, isReview: false, checked: false },
      { idx: 5, isReview: false, checked: false },
      { idx: 6, isReview: false, checked: false },
      { idx: 7, isReview: false, checked: false },
      { idx: 8, isReview: false, checked: false },
      { idx: 9, isReview: false, checked: false },
      { idx: 10, isReview: false, checked: false },
    ],
  },
  {
    title: "Part2",
    children: [
      { idx: 11, isReview: false, checked: false },
      { idx: 12, isReview: false, checked: false },
      { idx: 13, isReview: false, checked: false },
      { idx: 14, isReview: false, checked: false },
      { idx: 15, isReview: false, checked: false },
      { idx: 16, isReview: false, checked: false },
      { idx: 17, isReview: false, checked: false },
      { idx: 18, isReview: false, checked: false },
      { idx: 19, isReview: false, checked: false },
      { idx: 20, isReview: false, checked: false },
    ],
  },
  {
    title: "Part3",
    children: [
      { idx: 21, isReview: false, checked: false },
      { idx: 22, isReview: false, checked: false },
      { idx: 23, isReview: false, checked: false },
      { idx: 24, isReview: false, checked: false },
      { idx: 25, isReview: false, checked: false },
      { idx: 26, isReview: false, checked: false },
      { idx: 27, isReview: false, checked: false },
      { idx: 28, isReview: false, checked: false },
      { idx: 29, isReview: false, checked: false },
      { idx: 30, isReview: false, checked: false },
    ],
  },
  {
    title: "Part4",
    children: [
      { idx: 31, isReview: false, checked: false },
      { idx: 32, isReview: false, checked: false },
      { idx: 33, isReview: false, checked: false },
      { idx: 34, isReview: false, checked: false },
      { idx: 35, isReview: false, checked: false },
      { idx: 36, isReview: false, checked: false },
      { idx: 37, isReview: false, checked: false },
      { idx: 38, isReview: false, checked: false },
      { idx: 39, isReview: false, checked: false },
      { idx: 40, isReview: false, checked: false },
    ],
  },
];
