export const listeningQuestionNumber: any[] = [
  {
    title: "Part1",
    children: [
      { idx: 1, isReview: false, checked: true },
      { idx: 2, isReview: false, checked: false },
      { idx: 3, isReview: false, checked: false },
      { idx: 4, isReview: false, checked: false },
      { idx: 5, isReview: false, checked: false },
      { idx: 6, isReview: false, checked: false },
      { idx: 7, isReview: false, checked: false },
      { idx: 8, isReview: false, checked: false },
      { idx: 9, isReview: false, checked: false },
      { idx: 10, isReview: false, checked: false },
    ],
  },
  {
    title: "Part2",
    children: [
      { idx: 1, isReview: false, checked: false },
      { idx: 2, isReview: false, checked: false },
      { idx: 3, isReview: false, checked: false },
      { idx: 4, isReview: false, checked: false },
      { idx: 5, isReview: false, checked: false },
      { idx: 6, isReview: false, checked: false },
      { idx: 7, isReview: false, checked: false },
      { idx: 8, isReview: false, checked: false },
      { idx: 9, isReview: false, checked: false },
      { idx: 10, isReview: false, checked: false },
    ],
  },
  {
    title: "Part3",
    children: [
      { idx: 1, isReview: false, checked: false },
      { idx: 2, isReview: false, checked: false },
      { idx: 3, isReview: false, checked: false },
      { idx: 4, isReview: false, checked: false },
      { idx: 5, isReview: false, checked: false },
      { idx: 6, isReview: false, checked: false },
      { idx: 7, isReview: false, checked: false },
      { idx: 8, isReview: false, checked: false },
      { idx: 9, isReview: false, checked: false },
      { idx: 10, isReview: false, checked: false },
    ],
  },
  {
    title: "Part4",
    children: [
      { idx: 1, isReview: false, checked: false },
      { idx: 2, isReview: false, checked: false },
      { idx: 3, isReview: false, checked: false },
      { idx: 4, isReview: false, checked: false },
      { idx: 5, isReview: false, checked: false },
      { idx: 6, isReview: false, checked: false },
      { idx: 7, isReview: false, checked: false },
      { idx: 8, isReview: false, checked: false },
      { idx: 9, isReview: false, checked: false },
      { idx: 10, isReview: false, checked: false },
    ],
  },
];
